import { useWeb3React } from "@web3-react/core";
import { connector } from "../config/web3";
import { useCallback, useEffect, useState } from "react";
import '../node_modules/koicss/css/styles.min.css'
import Head from "next/head";
import Header from "../components/header.component";
import Address from "../components/address.component";
import Balance from "../components/balance.component";
import Button from "../components/button.component";

export default function Home() {
  const { activate, active, deactivate, error, account, chainID, library } =
    useWeb3React();

  const [balance, setBalance] = useState(0);

  const connect = useCallback(() => {
    activate(connector);
    localStorage.setItem("previuslyWalletConnected", true);
  });

  const updateBalance = async () => {
    await library?.eth.getBalance(account).then((result) => {
      setBalance(result / 1e18);
    });
  };

  const disconnect = () => {
    deactivate();
    localStorage.removeItem("previuslyWalletConnected");
  };

  useEffect(() => {
    if (localStorage.getItem("previuslyWalletConnected") === "true") connect();
  }, [connect]);

  useEffect(() => {
    library?.eth.getBalance(account).then((result) => {
      setBalance(result / 1e18);
    });
  }, [library?.eth.getBalance(account)]);

  return (
    <div>
      <Head>
        <title>Web3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="center">
          <Header />
          {!active || !account ? (
            <Button text="log in" action={connect} />
          ) : (
            <div>
              <a
                href={`https://etherscan.io/address/${account}`}
                target="_blank"
                rel="nofollow noopener noreferrer"
              >
                <Address account={account} />
              </a>

                <Balance balance={balance} />
              <Button text="update balance" action={updateBalance} />

              <Button text="log out" action={disconnect} />
            </div>
          )}
      </main>
    </div>
  );
}
