import { useWeb3React } from '@web3-react/core';
import { connector } from '../config/web3'
import Head from 'next/head';
import { useCallback, useEffect, useState } from 'react';
import CachedIcon from '@mui/icons-material/Cached';

export default function Home() {
  const {activate, active, deactivate, error, account, chainID, library } = useWeb3React();
  
  const connect = useCallback(() => {
    activate(connector);
    localStorage.setItem('previuslyWalletConnected', true)
  });
  
    const [balance, setBalance] = useState(0);
    useEffect(() => {
      getMyBalance()
    }, [])
    
    const getMyBalance = async() => {
      const eth_balance = library.eth.getBalance(account).then(console.log('error'))
      const ethBalance = await eth_balance
      setBalance(ethBalance)
    }
  
  const disconnect = () => {
    deactivate();
    localStorage.removeItem('previuslyWalletConnected')
  };

  useEffect(() => {
    if(localStorage.getItem('previuslyWalletConnected') === "true") connect();
  }, [])

  
  return (
    <div className="min-h-screen">
      <Head>
        <title>Web3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center min-h-screen bg-blue-200">
        <div className="bg-white p-4 rounded-lg shadow-lg">
        <h1 className="text-center p-2 text-3xl font-semibold uppercase text-black-600">
          METAMASK WEB
        </h1>
            {!active || !account ? (
              <button onClick={connect} className='block w-full p-4 border-b-4 border-red-700 rounded-lg bg-red-500 text-white font-semibold uppercase text-lg leafing-none px-4 py-2'>
                Conectate con metamask
              </button> 
            ): (
              <div>
                <a href={`https://etherscan.io/address/${account}`} target="_blank" rel="nofollow noopener noreferrer" className='mt-2 block w-full text-center'> 
                  <span className='inline-block  border-b-4 border-red-20 w-[85%] text-black font-semibold truncate px-4 py-2 bg-gray-200 rounded-lg border-gray-300'>
                    {account}
                  </span>
                  
                </a>
                
              <div className='mt-2 block w-full text-center'>
              <span className="truncate text-lg w-[45%] text-black font-semibold uppercase bg-green-400 border-green-700 rounded-lg p-2 border-b-4">
                Balance: {balance/1000000000000000000}
              </span>
              </div>
              
              <button onClick={disconnect} className="inline-block mt-20 ml-8 w-[85%] border-b-4 border-red-700 rounded-lg bg-red-500 text-white font-semibold uppercase text-lg  py-2">
                Desconectarse
              </button>
              
                </div>
            )}

        </div>
      </main>
    </div>
  )
}

